on: [push]

jobs:
  label_job:
    runs-on: ubuntu-latest
    name: A job to label prs
    steps:
      - name: Label a pr when approved
        id: approved
        uses: msotoperdomo/label-prs-actions@v1
        with:
          task: 'label_pr_when_approved'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Use the output from the `approved` step
      - name: Get the output time
        run: echo "The time was ${{ steps.approved.outputs.time }}"