name: Label prs based on reviews
on: pull_request_review


jobs:
  label_pr_when_approved:
    runs-on: ubuntu-latest
    name: A job to label prs when approved
    steps:
      - name: Label a pr when approved
        id: approved
        uses: msotoperdomo/label-prs-actions@test-branch
        with:
          task: 'label_pr_when_approved'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APPROVALS: "1"
          ADD_LABEL: "approved"
      # Use the output from the `approved` step
      - name: Get the approval time
        run: echo "The time was ${{ steps.approved.outputs.time }}"
      - name: Remove a label from a pr
        id: remove_label
        uses: msotoperdomo/label-prs-actions@test-branch
        with:
          task: 'label_pr_remove'
        if: ${{ steps.approved.outputs.isApproved }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REMOVE_LABEL: "ready%20for%20review"
